version: '3.8'
services:
  eco-db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apartment-protection
    networks:
      - eco-network
networks:
  eco-network:
